# Generated by Django 2.2.1 on 2019-05-12 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasicData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_id', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=11)),
                ('address', models.CharField(max_length=50)),
                ('phoneNumber', models.CharField(max_length=15)),
                ('company', models.CharField(max_length=50)),
                ('job_title', models.CharField(max_length=15)),
                ('working_years', models.IntegerField()),
            ],
        ),
    ]
