# Generated by Django 2.2.1 on 2019-06-02 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankDepositData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('identity', models.CharField(max_length=15)),
                ('account', models.CharField(max_length=20)),
                ('performance', models.IntegerField(null=True)),
                ('opnning_data', models.DateTimeField(null=True)),
                ('a_year_average_balance', models.IntegerField(null=True)),
                ('six_month_average_balance', models.IntegerField(null=True)),
                ('refund_record', models.IntegerField(null=True)),
                ('seizure_deposit', models.IntegerField(null=True)),
                ('suspicious_account', models.BooleanField(null=True)),
                ('regularly_deposit_data_query', models.BooleanField(null=True)),
                ('yet_settled_data', models.BooleanField(null=True)),
                ('settled_data', models.BooleanField(null=True)),
                ('flexible_hand_money', models.BooleanField(null=True)),
                ('date_of_information', models.DateField(null=True)),
                ('three_months_assets', models.IntegerField(null=True)),
                ('AP', models.IntegerField(null=True)),
                ('not_ap', models.IntegerField(null=True)),
                ('last_ap', models.IntegerField(null=True)),
                ('last_not_ap', models.IntegerField(null=True)),
                ('debt_data_query', models.BooleanField(null=True)),
                ('oversea_deposit_data_query', models.BooleanField(null=True)),
                ('credit_card_data_query', models.BooleanField(null=True)),
                ('credit_card_BLOCK_CODE', models.BooleanField(null=True)),
                ('reject_case_data_query', models.BooleanField(null=True)),
                ('refuse_data_query', models.BooleanField(null=True)),
                ('advantage_and_disadvantage_relationships_data_query', models.BooleanField(null=True)),
                ('urge_system_error_data_query', models.BooleanField(null=True)),
                ('bank_JCIC_database', models.BooleanField(null=True)),
                ('credit_card_comment', models.BooleanField(null=True)),
                ('credit_card_JCIC_other_bank_data', models.BooleanField(null=True)),
                ('NCCCC_other_bank_reject_data', models.BooleanField(null=True)),
                ('e_collection_delay_day', models.IntegerField(null=True)),
                ('negotiate_data', models.BooleanField(null=True)),
                ('credit_card_other_bank_comment', models.BooleanField(null=True)),
                ('new_batch_processing_day', models.DateTimeField(null=True)),
                ('money_laundering_risk_degree', models.CharField(choices=[('VL', '非常高風險'), ('L', '低風險'), ('M', '中風險'), ('H', '高風險'), ('VH', '非常高風險')], default='VL', max_length=5)),
                ('priority_low', models.CharField(max_length=10, null=True)),
                ('background', models.CharField(max_length=50, null=True)),
                ('geographical_factor', models.CharField(max_length=50, null=True)),
                ('relation_behavior', models.CharField(max_length=50, null=True)),
                ('production', models.CharField(max_length=20, null=True)),
                ('money_laundering_risk_gradding', models.IntegerField(null=True)),
                ('FDD_information', models.BooleanField(null=True)),
                ('house_debt_judge_score', models.IntegerField(default=0)),
                ('car_debt_judge_score', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='BasicData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=11)),
                ('address', models.CharField(max_length=50)),
                ('person_phone', models.CharField(max_length=15)),
                ('person_house_phone', models.CharField(max_length=15)),
                ('company', models.CharField(max_length=50)),
                ('company_phone', models.CharField(max_length=15)),
                ('job_title', models.CharField(max_length=30)),
                ('career', models.IntegerField()),
                ('birthday', models.CharField(max_length=10)),
                ('company_address', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=500)),
            ],
        ),
    ]
