# Generated by Django 2.2.1 on 2019-05-13 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankDepositData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('identity', models.CharField(max_length=15)),
                ('account', models.CharField(max_length=20)),
                ('performance', models.IntegerField()),
                ('opnning_data', models.DateTimeField()),
                ('a_year_average_balance', models.IntegerField()),
                ('six_month_average_balance', models.IntegerField()),
                ('refund_record', models.IntegerField()),
                ('seizure_deposit', models.IntegerField()),
                ('suspicious_account', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='BasicData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=11)),
                ('address', models.CharField(max_length=50)),
                ('person_phone', models.CharField(default='0000000000', max_length=15)),
                ('person_house_phone', models.CharField(default='0000000000', max_length=15)),
                ('company', models.CharField(max_length=50)),
                ('company_phone', models.CharField(max_length=15)),
                ('job_title', models.CharField(max_length=30)),
                ('career', models.IntegerField()),
                ('birthday', models.CharField(default='00000', max_length=10)),
                ('company_address', models.CharField(default='', max_length=50)),
                ('description', models.TextField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('date_of_information', models.DateField()),
                ('three_months_assets', models.IntegerField()),
                ('AP', models.IntegerField()),
                ('not_ap', models.IntegerField()),
                ('last_ap', models.IntegerField()),
                ('last_not_ap', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FDDData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('identity', models.CharField(max_length=15)),
                ('new_batch_processing_day', models.DateTimeField()),
                ('money_laundering_risk_degree', models.CharField(choices=[('VL', '非常高風險'), ('L', '低風險'), ('M', '中風險'), ('H', '高風險'), ('VH', '非常高風險')], default='VL', max_length=5)),
                ('priority_low', models.CharField(max_length=10)),
                ('background', models.CharField(max_length=50)),
                ('geographical_factor', models.CharField(max_length=50)),
                ('relation_behavior', models.CharField(max_length=50)),
                ('production', models.CharField(max_length=20)),
                ('money_laundering_risk_gradding', models.IntegerField()),
                ('FDD_information', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='UnionSearchData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('identity', models.CharField(max_length=15)),
                ('EN_name', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=50)),
                ('birthday', models.DateField()),
            ],
        ),
    ]
