# Generated by Django 2.2.1 on 2019-05-12 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basicdata',
            old_name='working_years',
            new_name='career',
        ),
        migrations.RenameField(
            model_name='basicdata',
            old_name='phoneNumber',
            new_name='company_phone',
        ),
        migrations.AddField(
            model_name='basicdata',
            name='birthday',
            field=models.CharField(default='00000', max_length=8),
        ),
        migrations.AddField(
            model_name='basicdata',
            name='person_house_phone',
            field=models.CharField(default='0000000000', max_length=15),
        ),
        migrations.AddField(
            model_name='basicdata',
            name='person_phone',
            field=models.CharField(default='0000000000', max_length=15),
        ),
    ]
