# Generated by Django 2.2.1 on 2019-06-02 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdepositdata',
            name='money_laundering_risk_degree',
            field=models.CharField(choices=[('VL', '非常高風險'), ('L', '低風險'), ('M', '中風險'), ('H', '高風險'), ('VH', '非常高風險')], default='VH', max_length=5),
        ),
    ]
