# Generated by Django 2.2.1 on 2019-06-02 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0002_auto_20190602_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdepositdata',
            name='date_of_information',
            field=models.DateField(),
        ),
    ]
