# Generated by Django 2.2.1 on 2019-05-13 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0002_contribution_identity'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCardBasicData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_date', models.DateField()),
                ('institute', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=15)),
                ('birthday', models.DateField()),
                ('census', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('person_phone', models.CharField(max_length=15)),
                ('person_house_phone', models.CharField(max_length=15)),
                ('company', models.CharField(max_length=20)),
                ('job_title', models.CharField(max_length=50)),
                ('year_salary', models.IntegerField()),
                ('career', models.IntegerField()),
                ('edu_degree', models.CharField(choices=[('elementary', '小學'), ('junior', '國中'), ('senior', '高中'), ('undergraduated', '大學'), ('master', '碩士'), ('phd', '博士')], default='undergraduated', max_length=5)),
            ],
        ),
    ]
