# Generated by Django 2.2.1 on 2019-05-12 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0002_auto_20190512_0431'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicdata',
            name='company_address',
            field=models.CharField(default='', max_length=50),
        ),
    ]
