# Generated by Django 2.2.1 on 2019-05-12 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0003_basicdata_company_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicdata',
            name='birthday',
            field=models.CharField(default='00000', max_length=10),
        ),
    ]
