# Generated by Django 2.2.1 on 2019-06-22 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0003_auto_20190602_1243'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCardInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='UnionCreditCheckSystemInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=11)),
                ('eng_name', models.CharField(max_length=30)),
                ('birthday', models.DateField()),
                ('address', models.CharField(max_length=30)),
                ('other_info', models.CharField(default='N', max_length=15)),
                ('repay_info', models.CharField(default='N', max_length=15)),
                ('identity_card_reissue_record', models.IntegerField(default=0)),
                ('no_household_registration_in_TW', models.BooleanField(default=False)),
                ('refund_error_record', models.IntegerField(default=0)),
                ('recent_credit_problem', models.DateField(null=True)),
                ('bulletined_case_record', models.IntegerField(default=0)),
                ('cancel_debt_record', models.IntegerField(default=0)),
                ('reject_contact_record', models.BooleanField(default=False)),
                ('credits_problem_record', models.IntegerField(default=0)),
                ('forced_stopping_credit_card_record', models.IntegerField(default=0)),
                ('case_notification_record', models.TextField(default='無')),
                ('migration_record', models.TextField(default='無')),
                ('identity_modification_record', models.TextField(default='無')),
                ('supplement_comment_record', models.TextField(default='無')),
                ('identity_record', models.CharField(max_length=15)),
                ('reissue_code', models.IntegerField(default=0)),
                ('reissue_date', models.DateField()),
                ('birthdat_on_identity_system', models.DateField()),
                ('issue_place', models.CharField(default='台灣', max_length=15)),
                ('no_household_registration_in_TW_identity_information', models.TextField(default='無')),
                ('data_date', models.DateField()),
                ('financial_product_conflict_comment', models.TextField(default='無')),
                ('joint_debt', models.TextField(default='查資料庫中無本人擔任他戶之共同債務資訊')),
                ('debt', models.TextField(default='無')),
                ('other_information', models.TextField(verbose_name='無')),
                ('new_quota', models.TextField(default='無')),
                ('overdue_collection_of_bad_debts', models.TextField(default='無')),
                ('transfer_of_overdue_information_claims', models.TextField(default='無')),
                ('Personal_unincorporated_organizations_info', models.TextField(default='無')),
                ('data_info_date', models.DateField()),
                ('data_process_date', models.DateField()),
                ('change_date', models.DateField()),
                ('orgnization', models.CharField(max_length=20)),
                ('ch_name', models.CharField(max_length=11)),
                ('birthday_on_credit_system', models.DateField()),
                ('contact_address', models.TextField(default='')),
                ('regirster_address', models.TextField(default='')),
                ('contact_phone_number', models.TextField(default='')),
                ('company_phone_number', models.TextField(default='')),
                ('company', models.TextField(default='')),
                ('job_title', models.TextField(default='')),
                ('year_salary', models.IntegerField(default=0)),
                ('career', models.IntegerField(default=0)),
                ('edu_degree', models.CharField(choices=[('PHD', '博士'), ('MASTER', '碩士'), ('BAC', '學士'), ('SH', '高中'), ('JH', '國中'), ('ES', '國小'), ('NONE', '無')], default='SH', max_length=5)),
                ('owned_house', models.BooleanField(default=False)),
                ('new_business', models.IntegerField(default=0)),
                ('original_business', models.IntegerField(default=0)),
                ('new_and_original_business', models.IntegerField(default=0)),
                ('other_financial_org_query_after_quered', models.IntegerField(default=0)),
                ('financial_query_time', models.IntegerField(default=0)),
                ('score', models.IntegerField(default=0)),
            ],
        ),
    ]
