# Generated by Django 2.2.1 on 2019-05-13 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0003_creditcardbasicdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcardbasicdata',
            name='edu_degree',
            field=models.CharField(choices=[('elementary', '小學'), ('junior', '國中'), ('senior', '高中'), ('undergraduated', '大學'), ('master', '碩士'), ('phd', '博士')], default='undergraduated', max_length=20),
        ),
    ]
