# Generated by Django 2.2.1 on 2019-05-12 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0004_auto_20190512_0455'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicdata',
            name='description',
            field=models.CharField(default='', max_length=500),
        ),
    ]
