# Generated by Django 2.2.1 on 2019-05-13 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0004_auto_20190513_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcardbasicdata',
            name='identity',
            field=models.CharField(default='', max_length=15),
        ),
    ]
