# Generated by Django 2.2.1 on 2019-06-23 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0005_auto_20190623_0332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankdepositdata',
            name='opnning_data',
        ),
        migrations.AddField(
            model_name='bankdepositdata',
            name='openning_date',
            field=models.DateField(null=True),
        ),
    ]
