# Generated by Django 2.2.1 on 2019-05-12 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0005_basicdata_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicdata',
            name='job_title',
            field=models.CharField(max_length=30),
        ),
    ]
