# Generated by Django 2.2.1 on 2019-06-23 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0006_auto_20190623_0334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdepositdata',
            name='openning_date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
