# Generated by Django 2.2.1 on 2019-05-13 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0007_auto_20190513_0609'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basicdata',
            old_name='person_id',
            new_name='identity',
        ),
    ]
