# Generated by Django 2.2.1 on 2019-06-23 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0008_auto_20190623_0334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicdata',
            name='birthday',
            field=models.DateField(),
        ),
    ]
