# Generated by Django 2.2.1 on 2019-05-13 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0008_auto_20190513_0626'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankDepositData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('account', models.CharField(max_length=20)),
                ('performance', models.IntegerField()),
                ('opnning_data', models.DateTimeField()),
                ('a_year_average_balance', models.IntegerField()),
                ('six_month_average_balance', models.IntegerField()),
                ('refund_record', models.IntegerField()),
                ('seizure_deposit', models.IntegerField()),
                ('suspicious_account', models.BooleanField()),
            ],
        ),
    ]
