# Generated by Django 2.2.1 on 2019-05-13 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0009_bankdepositdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankdepositdata',
            name='identity',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
    ]
