# Generated by Django 2.2.1 on 2019-06-23 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0010_auto_20190623_0336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdepositdata',
            name='new_batch_processing_day',
            field=models.DateField(null=True),
        ),
    ]
