# Generated by Django 2.2.1 on 2019-05-13 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0010_bankdepositdata_identity'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContributionLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('identity', models.CharField(max_length=15)),
                ('new_batch_processing_day', models.DateTimeField()),
                ('money_laundering_risk_degree', models.CharField(choices=[('VL', 'Very Low'), ('L', 'Low'), ('M', 'Middle'), ('H', 'High'), ('VH', 'Very High')], max_length=5)),
                ('priority_low', models.CharField(max_length=10)),
                ('background', models.CharField(max_length=50)),
                ('geographical_factor', models.CharField(max_length=50)),
                ('relation_behavior', models.CharField(max_length=50)),
                ('production', models.CharField(max_length=20)),
                ('money_laundering_risk_gradding', models.IntegerField()),
                ('FDD_information', models.BooleanField()),
            ],
        ),
    ]
