# Generated by Django 2.2.1 on 2019-06-23 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0011_auto_20190623_0337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdepositdata',
            name='AP',
            field=models.IntegerField(default=0, verbose_name='當年度總AP'),
        ),
        migrations.AlterField(
            model_name='bankdepositdata',
            name='FDD_information',
            field=models.BooleanField(default=False, null=True, verbose_name='防制洗錢FDD系統'),
        ),
        migrations.AlterField(
            model_name='bankdepositdata',
            name='NCCCC_other_bank_reject_data',
            field=models.TextField(default='無', verbose_name='NCCCC他行強停名單'),
        ),
        migrations.AlterField(
            model_name='bankdepositdata',
            name='a_year_average_balance',
            field=models.IntegerField(default=0, null=True, verbose_name='一年平均餘額'),
        ),
        migrations.AlterField(
            model_name='bankdepositdata',
            name='account',
            field=models.CharField(max_length=20, verbose_name='帳號'),
        ),
        migrations.AlterField(
            model_name='bankdepositdata',
            name='advantage_and_disadvantage_relationships_data_query',
            field=models.TextField(default='無', verbose_name='利害關係人記錄查詢'),
        ),
        migrations.AlterField(
            model_name='bankdepositdata',
            name='background',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='客戶背景'),
        ),
        migrations.AlterField(
            model_name='bankdepositdata',
            name='bank_JCIC_database',
            field=models.TextField(default='無', verbose_name='銀行JCIC資料庫'),
        ),
        migrations.AlterField(
            model_name='bankdepositdata',
            name='car_debt_judge_score',
            field=models.IntegerField(default=0, verbose_name='車貸近一年行為評分卡評等'),
        ),
        migrations.AlterField(
            model_name='bankdepositdata',
            name='credit_card_BLOCK_CODE',
            field=models.TextField(default='無', verbose_name='信用卡BLOCK CODE'),
        ),
        migrations.AlterField(
            model_name='bankdepositdata',
            name='credit_card_JCIC_other_bank_data',
            field=models.TextField(default='無', verbose_name='信用卡JCIC他行強停名單'),
        ),
        migrations.AlterField(
            model_name='bankdepositdata',
            name='credit_card_comment',
            field=models.TextField(default='無', verbose_name='信用卡徵審授信註記'),
        ),
        migrations.AlterField(
            model_name='bankdepositdata',
            name='credit_card_data_query',
            field=models.TextField(default='無', verbose_name='信用卡往來資料查詢'),
        ),
        migrations.AlterField(
            model_name='bankdepositdata',
            name='credit_card_other_bank_comment',
            field=models.TextField(default='無', verbose_name='信用卡金融同業通報註記'),
        ),
        migrations.AlterField(
            model_name='bankdepositdata',
            name='date_of_information',
            field=models.DateField(verbose_name='資料日期'),
        ),
        migrations.AlterField(
            model_name='bankdepositdata',
            name='debt_data_query',
            field=models.TextField(default='無', verbose_name='企金主從債務查詢'),
        ),
        migrations.AlterField(
            model_name='bankdepositdata',
            name='e_collection_delay_day',
            field=models.IntegerField(default=3, verbose_name='e-collection最大逾期天數'),
        ),
        migrations.AlterField(
            model_name='bankdepositdata',
            name='flexible_hand_money',
            field=models.TextField(default='無', verbose_name='彈性繳款'),
        ),
        migrations.AlterField(
            model_name='bankdepositdata',
            name='geographical_factor',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='地域因素'),
        ),
        migrations.AlterField(
            model_name='bankdepositdata',
            name='house_debt_judge_score',
            field=models.IntegerField(default=0, verbose_name='房貸近一年行為評分卡評等'),
        ),
        migrations.AlterField(
            model_name='bankdepositdata',
            name='identity',
            field=models.CharField(max_length=15, verbose_name='身分證字號'),
        ),
        migrations.AlterField(
            model_name='bankdepositdata',
            name='last_ap',
            field=models.IntegerField(default=0, verbose_name='前一年度總AP'),
        ),
        migrations.AlterField(
            model_name='bankdepositdata',
            name='last_not_ap',
            field=models.IntegerField(default=0, verbose_name='前一年非放款AP'),
        ),
        migrations.AlterField(
            model_name='bankdepositdata',
            name='money_laundering_risk_degree',
            field=models.CharField(choices=[('VL', '非常高風險'), ('L', '低風險'), ('M', '中風險'), ('H', '高風險'), ('VH', '非常高風險')], default='VH', max_length=5, verbose_name='洗錢風險分級'),
        ),
        migrations.AlterField(
            model_name='bankdepositdata',
            name='money_laundering_risk_gradding',
            field=models.IntegerField(default=0, null=True, verbose_name='洗錢風險總得分'),
        ),
        migrations.AlterField(
            model_name='bankdepositdata',
            name='name',
            field=models.CharField(max_length=15, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='bankdepositdata',
            name='negotiate_data',
            field=models.TextField(default='無', verbose_name='消債協商記號'),
        ),
        migrations.AlterField(
            model_name='bankdepositdata',
            name='new_batch_processing_day',
            field=models.DateField(null=True, verbose_name='最新跑批日'),
        ),
        migrations.AlterField(
            model_name='bankdepositdata',
            name='not_ap',
            field=models.IntegerField(default=0, verbose_name='當年度非放款AP'),
        ),
        migrations.AlterField(
            model_name='bankdepositdata',
            name='openning_date',
            field=models.DateField(null=True, verbose_name='開戶日'),
        ),
        migrations.AlterField(
            model_name='bankdepositdata',
            name='oversea_deposit_data_query',
            field=models.TextField(default='無', verbose_name='利害關係人海外放款往來資料查詢'),
        ),
        migrations.AlterField(
            model_name='bankdepositdata',
            name='performance',
            field=models.IntegerField(default=0, null=True, verbose_name='績效行'),
        ),
        migrations.AlterField(
            model_name='bankdepositdata',
            name='priority_low',
            field=models.CharField(default='', max_length=10, null=True, verbose_name='優先法'),
        ),
        migrations.AlterField(
            model_name='bankdepositdata',
            name='production',
            field=models.CharField(default='', max_length=20, null=True, verbose_name='商品'),
        ),
        migrations.AlterField(
            model_name='bankdepositdata',
            name='refund_record',
            field=models.IntegerField(default=0, verbose_name='退票紀錄'),
        ),
        migrations.AlterField(
            model_name='bankdepositdata',
            name='refuse_data_query',
            field=models.TextField(default='無', verbose_name='支存拒往資料查詢'),
        ),
        migrations.AlterField(
            model_name='bankdepositdata',
            name='regularly_deposit_data_query',
            field=models.BooleanField(default=False, verbose_name='定期性存款往來資料查詢'),
        ),
        migrations.AlterField(
            model_name='bankdepositdata',
            name='reject_case_data_query',
            field=models.TextField(default='無', verbose_name='不予承作資料查詢'),
        ),
        migrations.AlterField(
            model_name='bankdepositdata',
            name='relation_behavior',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='業務關係與交易行為'),
        ),
        migrations.AlterField(
            model_name='bankdepositdata',
            name='seizure_deposit',
            field=models.IntegerField(default=0, verbose_name='扣押存款'),
        ),
        migrations.AlterField(
            model_name='bankdepositdata',
            name='settled_data',
            field=models.TextField(default='無', verbose_name='已結清資料'),
        ),
        migrations.AlterField(
            model_name='bankdepositdata',
            name='six_month_average_balance',
            field=models.IntegerField(default=0, verbose_name='六個月平均餘額'),
        ),
        migrations.AlterField(
            model_name='bankdepositdata',
            name='suspicious_account',
            field=models.BooleanField(default=True, verbose_name='可疑帳戶'),
        ),
        migrations.AlterField(
            model_name='bankdepositdata',
            name='three_months_assets',
            field=models.IntegerField(default=0, verbose_name='近三個月資產規模'),
        ),
        migrations.AlterField(
            model_name='bankdepositdata',
            name='urge_system_error_data_query',
            field=models.TextField(default='無', verbose_name='催收系統異常資料查詢'),
        ),
        migrations.AlterField(
            model_name='bankdepositdata',
            name='yet_settled_data',
            field=models.TextField(default='無', verbose_name='尚未結清資料'),
        ),
        migrations.AlterField(
            model_name='basicdata',
            name='address',
            field=models.CharField(max_length=50, verbose_name='住家地址'),
        ),
        migrations.AlterField(
            model_name='basicdata',
            name='birthday',
            field=models.DateField(verbose_name='生日'),
        ),
        migrations.AlterField(
            model_name='basicdata',
            name='career',
            field=models.IntegerField(verbose_name='年資'),
        ),
        migrations.AlterField(
            model_name='basicdata',
            name='company',
            field=models.CharField(max_length=50, verbose_name='公司'),
        ),
        migrations.AlterField(
            model_name='basicdata',
            name='company_address',
            field=models.CharField(max_length=50, verbose_name='公司地址'),
        ),
        migrations.AlterField(
            model_name='basicdata',
            name='company_phone',
            field=models.CharField(max_length=15, verbose_name='公司電話'),
        ),
        migrations.AlterField(
            model_name='basicdata',
            name='description',
            field=models.TextField(max_length=500, verbose_name='說明'),
        ),
        migrations.AlterField(
            model_name='basicdata',
            name='identity',
            field=models.CharField(max_length=15, verbose_name='身分證字號'),
        ),
        migrations.AlterField(
            model_name='basicdata',
            name='job_title',
            field=models.CharField(max_length=30, verbose_name='職業說明'),
        ),
        migrations.AlterField(
            model_name='basicdata',
            name='name',
            field=models.CharField(max_length=11, verbose_name='名字'),
        ),
        migrations.AlterField(
            model_name='basicdata',
            name='person_house_phone',
            field=models.CharField(max_length=15, verbose_name='個人住家電話'),
        ),
        migrations.AlterField(
            model_name='basicdata',
            name='person_phone',
            field=models.CharField(max_length=15, verbose_name='個人電話'),
        ),
        migrations.AlterField(
            model_name='unioncreditchecksysteminfo',
            name='Personal_unincorporated_organizations_info',
            field=models.TextField(default='無', verbose_name='個人餘催呆授信留向非法人組織資訊'),
        ),
        migrations.AlterField(
            model_name='unioncreditchecksysteminfo',
            name='address',
            field=models.CharField(max_length=30, verbose_name='戶籍地址'),
        ),
        migrations.AlterField(
            model_name='unioncreditchecksysteminfo',
            name='birthdat_on_identity_system',
            field=models.DateField(verbose_name='出生日期'),
        ),
        migrations.AlterField(
            model_name='unioncreditchecksysteminfo',
            name='birthday',
            field=models.DateField(verbose_name='出生日期'),
        ),
        migrations.AlterField(
            model_name='unioncreditchecksysteminfo',
            name='birthday_on_credit_system',
            field=models.DateField(verbose_name='出生日期'),
        ),
        migrations.AlterField(
            model_name='unioncreditchecksysteminfo',
            name='bulletined_case_record',
            field=models.IntegerField(default=0, verbose_name='通報案件紀錄'),
        ),
        migrations.AlterField(
            model_name='unioncreditchecksysteminfo',
            name='cancel_debt_record',
            field=models.IntegerField(default=0, verbose_name='消債其他註記'),
        ),
        migrations.AlterField(
            model_name='unioncreditchecksysteminfo',
            name='career',
            field=models.IntegerField(default=0, verbose_name='年資'),
        ),
        migrations.AlterField(
            model_name='unioncreditchecksysteminfo',
            name='case_notification_record',
            field=models.TextField(default='無', verbose_name='案件通報'),
        ),
        migrations.AlterField(
            model_name='unioncreditchecksysteminfo',
            name='ch_name',
            field=models.CharField(max_length=11, verbose_name='中文姓名'),
        ),
        migrations.AlterField(
            model_name='unioncreditchecksysteminfo',
            name='change_date',
            field=models.DateField(verbose_name='異動日期'),
        ),
        migrations.AlterField(
            model_name='unioncreditchecksysteminfo',
            name='company',
            field=models.TextField(default='', verbose_name='任職機構'),
        ),
        migrations.AlterField(
            model_name='unioncreditchecksysteminfo',
            name='company_phone_number',
            field=models.CharField(default='', max_length=20, verbose_name='任職電話'),
        ),
        migrations.AlterField(
            model_name='unioncreditchecksysteminfo',
            name='contact_address',
            field=models.TextField(default='', verbose_name='戶籍地址'),
        ),
        migrations.AlterField(
            model_name='unioncreditchecksysteminfo',
            name='contact_phone_number',
            field=models.CharField(default='', max_length=20, verbose_name='居住電話'),
        ),
        migrations.AlterField(
            model_name='unioncreditchecksysteminfo',
            name='credits_problem_record',
            field=models.IntegerField(default=0, verbose_name='授信異常紀錄'),
        ),
        migrations.AlterField(
            model_name='unioncreditchecksysteminfo',
            name='data_process_date',
            field=models.DateField(verbose_name='資料處理日期'),
        ),
        migrations.AlterField(
            model_name='unioncreditchecksysteminfo',
            name='debt',
            field=models.TextField(default='無', verbose_name='從債務('),
        ),
        migrations.AlterField(
            model_name='unioncreditchecksysteminfo',
            name='edu_degree',
            field=models.CharField(choices=[('PHD', '博士'), ('MASTER', '碩士'), ('BAC', '學士'), ('SH', '高中'), ('JH', '國中'), ('ES', '國小'), ('NONE', '無')], default='SH', max_length=5, verbose_name='教育程度'),
        ),
        migrations.AlterField(
            model_name='unioncreditchecksysteminfo',
            name='eng_name',
            field=models.CharField(max_length=30, verbose_name='英文姓名'),
        ),
        migrations.AlterField(
            model_name='unioncreditchecksysteminfo',
            name='financial_product_conflict_comment',
            field=models.TextField(default='無', verbose_name='衍生性金融商品交易轉捩授信爭議案件住記 '),
        ),
        migrations.AlterField(
            model_name='unioncreditchecksysteminfo',
            name='financial_query_time',
            field=models.IntegerField(default=0, verbose_name='金融機構查詢次數'),
        ),
        migrations.AlterField(
            model_name='unioncreditchecksysteminfo',
            name='forced_stopping_credit_card_record',
            field=models.IntegerField(default=0, verbose_name='強制停卡紀錄'),
        ),
        migrations.AlterField(
            model_name='unioncreditchecksysteminfo',
            name='identity',
            field=models.CharField(max_length=15, verbose_name='身分證字號'),
        ),
        migrations.AlterField(
            model_name='unioncreditchecksysteminfo',
            name='identity_card_reissue_record',
            field=models.IntegerField(default=0, verbose_name='身分證申請補發記錄'),
        ),
        migrations.AlterField(
            model_name='unioncreditchecksysteminfo',
            name='identity_modification_record',
            field=models.TextField(default='無', verbose_name='身分證更改記錄'),
        ),
        migrations.AlterField(
            model_name='unioncreditchecksysteminfo',
            name='identity_record',
            field=models.CharField(max_length=15, verbose_name='身分證更改紀錄'),
        ),
        migrations.AlterField(
            model_name='unioncreditchecksysteminfo',
            name='issue_place',
            field=models.CharField(default='台灣', max_length=15, verbose_name='發證地點'),
        ),
        migrations.AlterField(
            model_name='unioncreditchecksysteminfo',
            name='job_title',
            field=models.TextField(default='', verbose_name='職稱'),
        ),
        migrations.AlterField(
            model_name='unioncreditchecksysteminfo',
            name='joint_debt',
            field=models.TextField(default='查資料庫中無本人擔任他戶之共同債務資訊', verbose_name='共同債務 '),
        ),
        migrations.AlterField(
            model_name='unioncreditchecksysteminfo',
            name='migration_record',
            field=models.TextField(default='無', verbose_name='遷徙公告'),
        ),
        migrations.AlterField(
            model_name='unioncreditchecksysteminfo',
            name='name',
            field=models.CharField(max_length=11, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='unioncreditchecksysteminfo',
            name='new_and_original_business',
            field=models.IntegerField(default=0, verbose_name='原業務往來及新業務申請'),
        ),
        migrations.AlterField(
            model_name='unioncreditchecksysteminfo',
            name='new_business',
            field=models.IntegerField(default=0, verbose_name='新業務申請'),
        ),
        migrations.AlterField(
            model_name='unioncreditchecksysteminfo',
            name='new_quota',
            field=models.TextField(default='無', verbose_name='新增額度'),
        ),
        migrations.AlterField(
            model_name='unioncreditchecksysteminfo',
            name='no_household_registration_in_TW',
            field=models.BooleanField(default=False, verbose_name='在台無戶籍人士身分註記'),
        ),
        migrations.AlterField(
            model_name='unioncreditchecksysteminfo',
            name='no_household_registration_in_TW_identity_information',
            field=models.TextField(default='無', verbose_name='在台無戶籍人士身分證資料'),
        ),
        migrations.AlterField(
            model_name='unioncreditchecksysteminfo',
            name='orgnization',
            field=models.CharField(max_length=20, verbose_name='報送機構'),
        ),
        migrations.AlterField(
            model_name='unioncreditchecksysteminfo',
            name='original_business',
            field=models.IntegerField(default=0, verbose_name='原業務申請'),
        ),
        migrations.AlterField(
            model_name='unioncreditchecksysteminfo',
            name='other_financial_org_query_after_quered',
            field=models.IntegerField(default=0, verbose_name='查詢當日截至目前金融機構查詢次數'),
        ),
        migrations.AlterField(
            model_name='unioncreditchecksysteminfo',
            name='other_info',
            field=models.CharField(default='N', max_length=15, verbose_name='其餘資訊'),
        ),
        migrations.AlterField(
            model_name='unioncreditchecksysteminfo',
            name='other_information',
            field=models.TextField(default='無', verbose_name='其他'),
        ),
        migrations.AlterField(
            model_name='unioncreditchecksysteminfo',
            name='overdue_collection_of_bad_debts',
            field=models.TextField(default='無', verbose_name='逾期催收及呆帳資料'),
        ),
        migrations.AlterField(
            model_name='unioncreditchecksysteminfo',
            name='owned_house',
            field=models.BooleanField(default=False, verbose_name='自用住宅有無'),
        ),
        migrations.AlterField(
            model_name='unioncreditchecksysteminfo',
            name='recent_credit_problem',
            field=models.DateField(null=True, verbose_name='最近授信異常日期'),
        ),
        migrations.AlterField(
            model_name='unioncreditchecksysteminfo',
            name='refund_error_record',
            field=models.IntegerField(default=0, verbose_name='退票異常紀錄'),
        ),
        migrations.AlterField(
            model_name='unioncreditchecksysteminfo',
            name='regirster_address',
            field=models.TextField(default='', verbose_name='通訊地址'),
        ),
        migrations.AlterField(
            model_name='unioncreditchecksysteminfo',
            name='reissue_code',
            field=models.IntegerField(default=0, verbose_name='領補換代碼'),
        ),
        migrations.AlterField(
            model_name='unioncreditchecksysteminfo',
            name='reissue_date',
            field=models.DateField(verbose_name='領補換日期'),
        ),
        migrations.AlterField(
            model_name='unioncreditchecksysteminfo',
            name='reject_contact_record',
            field=models.BooleanField(default=False, verbose_name='拒絕往來紀錄'),
        ),
        migrations.AlterField(
            model_name='unioncreditchecksysteminfo',
            name='repay_info',
            field=models.CharField(default='N', max_length=15, verbose_name='新增額度及每筆撥款清償資訊'),
        ),
        migrations.AlterField(
            model_name='unioncreditchecksysteminfo',
            name='score',
            field=models.IntegerField(default=0, verbose_name='信用評分'),
        ),
        migrations.AlterField(
            model_name='unioncreditchecksysteminfo',
            name='supplement_comment_record',
            field=models.TextField(default='無', verbose_name='補充註記資訊'),
        ),
        migrations.AlterField(
            model_name='unioncreditchecksysteminfo',
            name='transfer_of_overdue_information_claims',
            field=models.TextField(default='無', verbose_name='逾期資料債權轉讓'),
        ),
        migrations.AlterField(
            model_name='unioncreditchecksysteminfo',
            name='year_salary',
            field=models.IntegerField(default=0, verbose_name='年薪'),
        ),
    ]
