# Generated by Django 2.2.1 on 2019-06-23 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0012_auto_20190623_0402'),
    ]

    operations = [
        migrations.AddField(
            model_name='unioncreditchecksysteminfo',
            name='identity_data_date',
            field=models.DateField(null=True, verbose_name='資料日期'),
        ),
    ]
