# Generated by Django 2.2.1 on 2019-05-13 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0012_auto_20190513_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributionlevel',
            name='money_laundering_risk_degree',
            field=models.CharField(choices=[('VL', '非常高風險'), ('L', '低風險'), ('M', '中風險'), ('H', '高風險'), ('VH', '非常高風險')], default='VL', max_length=5),
        ),
    ]
