# Generated by Django 2.2.1 on 2019-06-23 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0013_unioncreditchecksysteminfo_identity_data_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unioncreditchecksysteminfo',
            name='data_date',
        ),
        migrations.AddField(
            model_name='unioncreditchecksysteminfo',
            name='extend_credit_data_date',
            field=models.DateField(null=True, verbose_name='授信保證資料日期'),
        ),
    ]
