# Generated by Django 2.2.1 on 2019-05-13 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0013_auto_20190513_1447'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContributionLevel',
            new_name='FDDData',
        ),
    ]
