# Generated by Django 2.2.1 on 2019-06-23 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0014_auto_20190623_0617'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.FloatField(default=0.0, verbose_name='完成度')),
                ('apply_department', models.CharField(default='消金業務部', max_length=20)),
                ('debt_type', models.CharField(max_length=20, verbose_name='貸款種類')),
                ('case_property', models.CharField(max_length=20, verbose_name='案件性質')),
                ('comment', models.BooleanField(default=False, verbose_name='本行註記')),
                ('union_check_system_comment', models.BooleanField(default=False, verbose_name='聯徵註記')),
                ('case_comment', models.BooleanField(default=False, verbose_name='案件註記')),
                ('special_interview', models.CharField(default='特殊時段', max_length=20, verbose_name='特殊照會')),
                ('check_info', models.CharField(default='遠端', max_length=20, verbose_name='審查資訊')),
            ],
        ),
    ]
