# Generated by Django 2.2.1 on 2019-06-23 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0015_case'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='identity',
            field=models.CharField(default='', max_length=20, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='case',
            name='apply_department',
            field=models.CharField(default='消金業務部', max_length=20, verbose_name='部門'),
        ),
        migrations.AlterField(
            model_name='case',
            name='case_property',
            field=models.CharField(default='新建', max_length=20, verbose_name='案件性質'),
        ),
    ]
