# Generated by Django 2.2.1 on 2019-06-23 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0016_auto_20190623_0733'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='name',
            field=models.CharField(default='', max_length=20, verbose_name='名字'),
        ),
    ]
