# Generated by Django 2.2.1 on 2019-06-23 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0017_case_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdepositdata',
            name='regularly_deposit_data_query',
            field=models.TextField(default='無', verbose_name='定期性存款往來資料查詢'),
        ),
    ]
