# Generated by Django 2.2.1 on 2019-06-24 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0018_auto_20190623_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicdata',
            name='job_type',
            field=models.CharField(default='服物業', max_length=20, verbose_name='行業別'),
        ),
    ]
